### ISSUE TITLE
can you give me a simple rsa example code for encrpyt text message like "abc", Thank you very much!

### ISSUE THREAD

**Issue by losenineai** [quarkslab/BVWhiteBox#1]

**Comment by doegox** [comment]
Sorry but this repo does not implement RSA but another asymmetric scheme

**Comment by losenineai** [comment]
> 

what asymmetric schme does this repo  implement ? anyway .how can I get some public open source for asymmetric whitebox implement？

**Comment by doegox** [comment]
please read the README.md, it's literally the first sentence

**Comment by losenineai** [comment]
@doegox  thanks for your patience.
